#!/usr/bin/env bash
# seed-prod.sh — Run prisma/seed.ts against the production database.
#
# Usage:
#   ./scripts/seed-prod.sh
#
# The script will prompt for the production DATABASE_URL and DIRECT_URL,
# swap them into .env for the duration of the seed, then restore the
# original .env automatically — even if the seed fails.

set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"
BACKUP_FILE="${ENV_FILE}.bak"

# ── Cleanup trap — always restore .env ───────────────────────────────────────
cleanup() {
  if [[ -f "$BACKUP_FILE" ]]; then
    mv "$BACKUP_FILE" "$ENV_FILE"
    echo ""
    echo "✓ .env restored to dev credentials."
  fi
}
trap cleanup EXIT

# ── Prompt for production credentials ────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════"
echo "  PeeHub — Production Seed"
echo "═══════════════════════════════════════════════════"
echo ""
echo "Enter the PRODUCTION Neon connection strings."
echo "These are used only for this seed run and are never saved."
echo ""

read -rp "PROD DATABASE_URL (pooler): " PROD_DATABASE_URL
read -rp "PROD DIRECT_URL   (direct): " PROD_DIRECT_URL
read -rp "ADMIN_EMAIL       [admin@peehub.com]: " PROD_ADMIN_EMAIL
PROD_ADMIN_EMAIL="${PROD_ADMIN_EMAIL:-admin@peehub.com}"
read -rsp "ADMIN_PASSWORD: " PROD_ADMIN_PASSWORD
echo ""
read -rp "ADMIN_FULL_NAME   [PeeHub Admin]: " PROD_ADMIN_FULL_NAME
PROD_ADMIN_FULL_NAME="${PROD_ADMIN_FULL_NAME:-PeeHub Admin}"

echo ""
echo "─── Summary ────────────────────────────────────────"
echo "  SEED_MODE    : prod  (networks + bundles + admin only)"
echo "  ADMIN_EMAIL  : $PROD_ADMIN_EMAIL"
echo "  ADMIN_NAME   : $PROD_ADMIN_FULL_NAME"
echo "────────────────────────────────────────────────────"
echo ""
read -rp "Proceed with production seed? [y/N] " CONFIRM
if [[ "${CONFIRM,,}" != "y" ]]; then
  echo "Aborted."
  exit 0
fi

# ── Swap .env ─────────────────────────────────────────────────────────────────
cp "$ENV_FILE" "$BACKUP_FILE"

cat > "$ENV_FILE" <<EOF
# Temporary production overrides — generated by seed-prod.sh
# The original .env is restored automatically after the seed completes.

DATABASE_URL="${PROD_DATABASE_URL}"
DIRECT_URL="${PROD_DIRECT_URL}"
NEXT_PUBLIC_APP_URL="https://peehub.hdolabs.com"

ADMIN_EMAIL="${PROD_ADMIN_EMAIL}"
ADMIN_PASSWORD="${PROD_ADMIN_PASSWORD}"
ADMIN_FULL_NAME="${PROD_ADMIN_FULL_NAME}"
DEMO_USER_EMAIL="demo@peehub.com"
DEMO_USER_PASSWORD="Demo1234!"
DEMO_USER_FULL_NAME="Demo User"
EOF

# ── Run seed ──────────────────────────────────────────────────────────────────
echo ""
echo "Running production seed..."
echo ""

SEED_MODE=prod npx prisma db seed

echo ""
echo "✓ Production seed complete."
